[package]
name = "uyem-server"
version = "0.1.0"
edition = "2021"
description = "WebRTC SFU server"
authors = ["Sergey Kolmiller <uyem.ru@gmail.com>"]
license = "MIT"
readme = "README.md"
keywords = []
categories = []
repository = ""
include = ["Cargo.toml", "/src/*.rs", "src/**/*.rs"]
rust-version = "1.67"

[[bin]]
name = "server"

[lib]
name = "uyem_server"

[dependencies]
env_logger = "0.10.0"
log = { version = "0.4.17", features = [ "max_level_debug", "release_max_level_warn" ] }
serde = { version = "1.0.154", features = [ "derive" ] }
serde_json = { version = "1.0.94", default-features = false, features = ["alloc"] }
webrtc = "0.7.1"
tokio = { version = "1.26.0", features = ["full"] }
tokio-tungstenite = { version = "0.18.0", features = ["native-tls"]}
futures-util = "0.3.27"
once_cell = "1.17.1"
futures = "0.3.27"
url = "2.3.1"
dotenvy = "0.15.6"

[dependencies.uuid]
version = "1.3.0"
features = [
    "v4",              
    "fast-rng",          
    "macro-diagnostics"
]
