[package]
name = "server-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.10.0"
log = { version = "0.4.17", features = [ "max_level_debug", "release_max_level_warn" ] }
serde = { version = "1.0.154", features = [ "derive" ] }
serde_json = { version = "1.0.94", default-features = false, features = ["alloc"] }
tungstenite = "0.18.0"
webrtc = "0.7.1"
tokio = { version = "1.26.0", features = ["full"] }
tokio-tungstenite = "0.18.0"
futures-util = "0.3.27"
once_cell = "1.17.1"

[dependencies.uuid]
version = "1.3.0"
features = [
    "v4",              
    "fast-rng",          
    "macro-diagnostics"
]
