[package]
name = "server-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.10.0"
log = { version = "0.4.17", features = [ "max_level_debug", "release_max_level_warn" ] }
serde = { version = "1.0.154", features = [ "derive" ] }
serde_json = { version = "1.0.94", default-features = false, features = ["alloc"] }
ws = { version = "0.9.2", features = [ "native-tls" ] }

[dependencies.uuid]
version = "1.3.0"
features = [
    "v4",              
    "fast-rng",          
    "macro-diagnostics"
]
